/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SqlSandboxRouteImport } from './routes/sql-sandbox'
import { Route as GameCenterRouteImport } from './routes/game-center'
import { Route as IndexRouteImport } from './routes/index'

const SqlSandboxRoute = SqlSandboxRouteImport.update({
  id: '/sql-sandbox',
  path: '/sql-sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCenterRoute = GameCenterRouteImport.update({
  id: '/game-center',
  path: '/game-center',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game-center': typeof GameCenterRoute
  '/sql-sandbox': typeof SqlSandboxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game-center': typeof GameCenterRoute
  '/sql-sandbox': typeof SqlSandboxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game-center': typeof GameCenterRoute
  '/sql-sandbox': typeof SqlSandboxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game-center' | '/sql-sandbox'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game-center' | '/sql-sandbox'
  id: '__root__' | '/' | '/game-center' | '/sql-sandbox'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameCenterRoute: typeof GameCenterRoute
  SqlSandboxRoute: typeof SqlSandboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sql-sandbox': {
      id: '/sql-sandbox'
      path: '/sql-sandbox'
      fullPath: '/sql-sandbox'
      preLoaderRoute: typeof SqlSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-center': {
      id: '/game-center'
      path: '/game-center'
      fullPath: '/game-center'
      preLoaderRoute: typeof GameCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameCenterRoute: GameCenterRoute,
  SqlSandboxRoute: SqlSandboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
