/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeMachineRouteImport } from './routes/time-machine'
import { Route as SqlSandboxRouteImport } from './routes/sql-sandbox'
import { Route as GameCenterRouteImport } from './routes/game-center'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'

const TimeMachineRoute = TimeMachineRouteImport.update({
  id: '/time-machine',
  path: '/time-machine',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlSandboxRoute = SqlSandboxRouteImport.update({
  id: '/sql-sandbox',
  path: '/sql-sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCenterRoute = GameCenterRouteImport.update({
  id: '/game-center',
  path: '/game-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/game-center': typeof GameCenterRoute
  '/sql-sandbox': typeof SqlSandboxRoute
  '/time-machine': typeof TimeMachineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/game-center': typeof GameCenterRoute
  '/sql-sandbox': typeof SqlSandboxRoute
  '/time-machine': typeof TimeMachineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/game-center': typeof GameCenterRoute
  '/sql-sandbox': typeof SqlSandboxRoute
  '/time-machine': typeof TimeMachineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat' | '/game-center' | '/sql-sandbox' | '/time-machine'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat' | '/game-center' | '/sql-sandbox' | '/time-machine'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/game-center'
    | '/sql-sandbox'
    | '/time-machine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  GameCenterRoute: typeof GameCenterRoute
  SqlSandboxRoute: typeof SqlSandboxRoute
  TimeMachineRoute: typeof TimeMachineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/time-machine': {
      id: '/time-machine'
      path: '/time-machine'
      fullPath: '/time-machine'
      preLoaderRoute: typeof TimeMachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql-sandbox': {
      id: '/sql-sandbox'
      path: '/sql-sandbox'
      fullPath: '/sql-sandbox'
      preLoaderRoute: typeof SqlSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-center': {
      id: '/game-center'
      path: '/game-center'
      fullPath: '/game-center'
      preLoaderRoute: typeof GameCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  GameCenterRoute: GameCenterRoute,
  SqlSandboxRoute: SqlSandboxRoute,
  TimeMachineRoute: TimeMachineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
